### ISSUE TITLE
BedrockEconomy requires xbox authentication.

### ISSUE THREAD

**Issue by LinQu** [cooldogedev/BedrockEconomy#123] opened 2024-02-17 11:21 UTC
i user waterdogpe proxy and in server server.properties xba is off and then crash get message " BedrockEconomy requires xbox authentication.", if i change xba on get no authentication why?
hwo to solve help me
thanks

**Comment by SkulZOnTheYT** [comment] 2024-02-17 12:45
> i user waterdogpe proxy and in server server.properties xba is off and then crash get message " BedrockEconomy requires xbox authentication.", if i change xba on get no authentication why? hwo to solve help me thanks

use bedrock economy version below version 4

**Comment by cooldogedev** [comment] 2024-02-17 14:40
Enable login extras in WDPE and use this [plugin](https://github.com/cooldogepm/WDPELoginExtras)

**Comment by cooldogedev** [comment] 2024-02-17 14:41
Duplicate of https://github.com/cooldogepm/BedrockEconomy/issues/115

**Closed as completed by cooldogedev** 2024-02-17 14:40 UTC
Labels: Type: Question, Category: Core
