### ISSUE TITLE
Commands dont register properly

### ISSUE THREAD

**Issue by ParadoxPlays** [cooldogedev/BedrockEconomy#118] opened 2024-01-04 05:25 UTC
When I do a command for example /balance, it doesn't register (It doesnt actually show the "Your balance is" until you type it again.
This seems to also extend to other plugins that use economy such as CustomShopUI where when you buy something it doesn't actually register until you for instance type /shop again.

**Comment by cooldogedev** [comment] 2024-01-05 16:55
Can you provide more information such as the server's version as well as BedrockEconomy's and your `config.yml` (without credentials if you're using the mysql provider)

**Comment by EpixPlays** [comment] 2024-01-05 19:43
This issue is happening with me as well. I'm using the latest server version and the issue is that commands don't run on the first run. You need to run an additional command for the first to work. Sometimes that doesn't even work. I use chestshop to purchase items and when you purchase something you need to run another command such as /balance for the purchase to go through.

**Comment by cooldogedev** [comment] 2024-01-06 13:52
> This issue is happening with me as well. I'm using the latest server version and the issue is that commands don't run on the first run. You need to run an additional command for the first to work. Sometimes that doesn't even work. I use chestshop to purchase items and when you purchase something you need to run another command such as /balance for the purchase to go through.

Can you provide more information such as the server's version as well as BedrockEconomy's and your config.yml (without credentials if you're using the mysql provider)

**Comment by ParadoxPlays** [comment] 2024-01-07 03:03
It works sometimes but normally it doesn't work properly for instance if you type /balance, instead of it immediately showing your balance, it instead makes you type out /balance again to show it the first time (not sure if you can type any other command), I don't know if this is related either but scorehud for bedrock economy doesn't update unlesss you relog either.
Server Version 1.12.50
Pocketmine Version: 5.10.0
Bedrock Economy Version: v2.1.2
config:
---
config-version: 2.1.2
language: en-US
utility:
  top-balance-accounts-limit: 10
currency:
  name: USD
  symbol: $
  number-separator: ','
  balance:
    default-balance: 100
    balance-cap: 100000
    enable-balance-cap: false
  payment:
    minimum-payment: 100
    maximum-payment: 1000
database:
  provider: sqlite
  threads: 2
  mysql:
    host: 127.0.0.1
    username: your_username
    password: password
    schema: db_name
    port: 3306
  sqlite:
    path: players.db
...

**Comment by cooldogedev** [comment] 2024-01-07 14:47
> ## It works sometimes but normally it doesn't work properly for instance if you type /balance, instead of it immediately showing your balance, it instead makes you type out /balance again to show it the first time (not sure if you can type any other command), I don't know if this is related either but scorehud for bedrock economy doesn't update unlesss you relog either.
> Server Version 1.12.50
> Pocketmine Version: 5.10.0
> Bedrock Economy Version: v2.1.2
> config:
> config-version: 2.1.2 language: en-US utility: top-balance-accounts-limit: 10 currency: name: USD symbol: $ number-separator: ',' balance: default-balance: 100 balance-cap: 100000 enable-balance-cap: false payment: minimum-payment: 100 maximum-payment: 1000 database: provider: sqlite threads: 2 mysql: host: 127.0.0.1 username: your_username password: password schema: db_name port: 3306 sqlite: path: players.db ...

Can you try setting your database threads to 1 and see if it still happens?

**Comment by ParadoxPlays** [comment] 2024-01-07 16:12
Setting database threads to 1 did not seem to fix the issue.

**Comment by ParadoxPlays** [comment] 2024-01-07 18:55
I recorded this video showing the database thread amount aswell as the command error that I have. Had to upload it to youtube because it was too large of a file size to upload to github.
https://youtu.be/kEXWlfWa08I?si=aQEF3Mo01xptmTo1

**Comment by cooldogedev** [comment] 2024-01-07 19:08
> I recorded this video showing the database thread amount aswell as the command error that I have. Had to upload it to youtube because it was too large of a file size to upload to github. https://youtu.be/kEXWlfWa08I?si=aQEF3Mo01xptmTo1

Can you try using this [dev build](https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy/BedrockEconomy/dev:107)

**Comment by cooldogedev** [comment] 2024-01-07 19:12
If the issue persists, try using BedrockEconomy in a fresh server (with no other plugins)

**Comment by ParadoxPlays** [comment] 2024-01-07 19:23
The dev build seems to have fixed the issue.

**Comment by cooldogedev** [comment] 2024-01-07 23:16
Use the latest version [v4.0.0](https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy/BedrockEconomy/dev:107) which will be released on Poggit soon. v2.x.x is  under EOL

**Closed as completed by cooldogedev** 2024-01-07 23:16 UTC
Labels: Type: Bug, Category: Core, Status: Unconfirmed
